#!/usr/bin/env python3
"""Generate the MODELLED complex-refractive-index tables (roadmap M7.5).

    python scripts/generate_nk_tables.py --out data/nk

`data/nk/water.csv` is a measured table (Segelstein 1981) and is **not** touched by this script.
What this generates is the metal, for which a measured table was not obtainable here and for which
there is a standard closed-form model that is good in the infrared.

Aluminium: the Drude free-electron model,

    eps(w) = 1 - wp^2 / (w^2 + i Gamma w)

which is the right physics for a metal far below its plasma frequency -- the infrared response of
Al is free-carrier response, and interband structure sits in the ultraviolet. The two parameters
are chosen so the model reproduces the commonly quoted n = 25.3, k = 89.8 at 10 um; they come out
at wp = 12.53 eV and Gamma = 0.0759 eV, both inside the spread of published Drude fits for Al.

Why this matters enough to model rather than skip: M7.7 enforces §4.2's rule that a constant
emissivity is only acceptable above eps = 0.93, and bare aluminium is nowhere near it. Level B
cannot help either -- a metal's emissivity *rises* with angle and the Level B form cannot represent
that at any (a, p). So aluminium has no valid angular model without an n/k table, and any scene
containing bare metal raises rather than rendering a flat limb.
"""

from __future__ import annotations

import argparse
import pathlib

import numpy as np
from numpy.typing import NDArray

#: Drude parameters in eV, fitted to reproduce n = 25.3, k = 89.8 at 10 um.
ALUMINIUM_PLASMA_EV = 12.53
ALUMINIUM_DAMPING_EV = 0.0759
EV_UM = 1.2398419843320026  # h c / e, so that E[eV] = EV_UM / lambda[um]

LAMBDA_MIN_UM, LAMBDA_MAX_UM, N_POINTS = 0.6, 25.0, 400


def drude_nk(
    lam_um: NDArray[np.float64], plasma_ev: float, damping_ev: float
) -> tuple[NDArray[np.float64], NDArray[np.float64]]:
    """n and k from the Drude dielectric function, via the passive branch of sqrt(eps)."""
    omega = EV_UM / lam_um
    eps = 1.0 - plasma_ev**2 / (omega * (omega + 1j * damping_ev))
    modulus = np.abs(eps)
    n = np.sqrt(np.maximum(0.0, 0.5 * (modulus + eps.real)))
    k = np.sqrt(np.maximum(0.0, 0.5 * (modulus - eps.real)))
    return np.asarray(n), np.asarray(k)


HEADER = """\
# Complex refractive index of bare aluminium, n(lambda) + i k(lambda), {lo}-{hi} um.
#
# source: MODELLED, NOT MEASURED -- the Drude free-electron model
#   eps(w) = 1 - wp^2 / (w^2 + i Gamma w), with wp = {wp} eV and Gamma = {gamma} eV.
#   Free-carrier response is the right physics for a metal far below its plasma frequency, which
#   the whole infrared is; aluminium's interband structure sits in the ultraviolet. The two
#   parameters are chosen so the model reproduces the commonly quoted n = 25.3, k = 89.8 at
#   10 um, and both land inside the spread of published Drude fits for Al. Replace with a
#   measured table (Ordal et al. 1985, or Rakic et al. 1998) when one is obtainable; the loader
#   and every consumer are unchanged by the swap.
#
# Generated by scripts/generate_nk_tables.py on 2026-09-15 (roadmap M7.5).
# Check values from this model: n({q1} um) = {n1:.2f}, k = {k1:.2f}; n({q2} um) = {n2:.2f},
#   k = {k2:.2f}. Normal-incidence emissivity at 10 um: {e10:.5f}.
# Columns: wavelength in MICROMETRES, then n, then k.
wavelength_um,n,k
"""


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", default="data/nk")
    args = parser.parse_args(argv)
    out = pathlib.Path(args.out)
    out.mkdir(parents=True, exist_ok=True)

    lam = np.geomspace(LAMBDA_MIN_UM, LAMBDA_MAX_UM, N_POINTS)
    n, k = drude_nk(lam, ALUMINIUM_PLASMA_EV, ALUMINIUM_DAMPING_EV)
    n10 = float(np.interp(10.0, lam, n))
    k10 = float(np.interp(10.0, lam, k))
    r0 = ((n10 - 1.0) ** 2 + k10**2) / ((n10 + 1.0) ** 2 + k10**2)

    path = out / "aluminium.csv"
    path.write_text(
        HEADER.format(
            lo=LAMBDA_MIN_UM,
            hi=LAMBDA_MAX_UM,
            wp=ALUMINIUM_PLASMA_EV,
            gamma=ALUMINIUM_DAMPING_EV,
            q1=4.0,
            n1=float(np.interp(4.0, lam, n)),
            k1=float(np.interp(4.0, lam, k)),
            q2=10.0,
            n2=n10,
            k2=k10,
            e10=1.0 - r0,
        )
        + "\n".join(f"{a:.5f},{b:.5f},{c:.5f}" for a, b, c in zip(lam, n, k, strict=True))
        + "\n",
        encoding="utf-8",
    )
    print(f"wrote {path} ({lam.size} rows)")
    for q in (1.0, 4.0, 10.0, 20.0):
        nq, kq = float(np.interp(q, lam, n)), float(np.interp(q, lam, k))
        rq = ((nq - 1.0) ** 2 + kq**2) / ((nq + 1.0) ** 2 + kq**2)
        print(f"   {q:5.1f} um: n = {nq:7.2f}  k = {kq:7.2f}  eps(0) = {1.0 - rq:.5f}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
