#!/usr/bin/env python3
"""Regenerate the committed synthetic weather sample (M6.2, ADR 0032).

    python scripts/generate_weather.py [--out data/weather/clear_midlat_summer_48h.csv]

The arguments below ARE the definition of the file; tests/unit/test_weather_io.py regenerates it
with the same call and requires a bit-exact match, so change them here and re-run.
"""

from __future__ import annotations

import argparse
import pathlib
import sys
from datetime import datetime, timezone

REPO = pathlib.Path(__file__).resolve().parents[1]
DEFAULT_OUT = REPO / "data" / "weather" / "clear_midlat_summer_48h.csv"

SAMPLE_ARGS: dict[str, float] = {
    "hours": 48.0,
    "utc_offset_h": 2.0,  # central European summer time: a mid-latitude June day
    "t_mean_k": 295.15,
    "t_swing_k": 12.0,
    "t_max_hour_local": 15.0,
    "dewpoint_k": 285.15,
    "wind_speed_m_s": 2.5,
    "cloud_fraction": 0.05,
    "dni_peak_w_m2": 850.0,
    "dhi_peak_w_m2": 110.0,
    "sunrise_hour_local": 5.5,
    "sunset_hour_local": 21.0,
    "visibility_m": 23000.0,
    "step_s": 3600.0,
}
SAMPLE_START = datetime(2024, 6, 21, 0, 0, tzinfo=timezone.utc)
SAMPLE_COMMENT = (
    "SYNTHETIC clear mid-latitude summer day, 48 h from 2024-06-21T00:00Z, local = UTC+2.\n"
    "Generated by scripts/generate_weather.py (irsim.thermal.weather_io.synthetic_clear_day):\n"
    "sinusoidal T_air 295.15 +- 6 K (max 15:00 local), RH from a 12 C dew point, half-sine\n"
    "DNI 850 / DHI 110 W m^-2 peak between 05:30 and 21:00 local, wind 2.5 m/s, cloud 0.05,\n"
    "visibility 23 km. Not a measurement; a documented fixture (ADR 0032)."
)


# A coastal day for the maritime scenes (MM.6). Same generator, different water: a sea breeze
# that is calm at dawn and blows 9 m/s by mid-afternoon, over a sea whose temperature barely moves.
# The wind is the point -- it sets the Cox-Munk slope statistics the infrared sea reads AND the
# wave amplitude the visible surface is built from, so a maritime scene run on the constant
# 2.5 m/s inland fixture is a glassy sea all day, which is neither interesting nor typical.
COASTAL_ARGS: dict[str, float] = {
    "hours": 48.0,
    "utc_offset_h": 1.0,  # western Mediterranean
    "t_mean_k": 295.65,
    "t_swing_k": 6.0,  # maritime: the sea damps the diurnal swing to half the inland one
    "t_max_hour_local": 15.0,
    "dewpoint_k": 289.15,  # humid marine air, RH ~ 0.7
    "wind_speed_m_s": 5.5,
    "wind_swing_m_s": 7.0,  # 2.0 m/s at dawn to 9.0 m/s mid-afternoon
    "wind_max_hour_local": 16.0,
    "cloud_fraction": 0.10,
    "dni_peak_w_m2": 880.0,
    "dhi_peak_w_m2": 130.0,
    "sunrise_hour_local": 6.0,
    "sunset_hour_local": 20.5,
    "visibility_m": 30000.0,
    "step_s": 3600.0,
}
COASTAL_OUT = REPO / "data" / "weather" / "coastal_sea_breeze_48h.csv"
COASTAL_START = datetime(2024, 6, 21, 0, 0, tzinfo=timezone.utc)
COASTAL_COMMENT = (
    "SYNTHETIC coastal summer day with a sea breeze, 48 h from 2024-06-21T00:00Z, local = UTC+1.\n"
    "Generated by scripts/generate_weather.py (irsim.thermal.weather_io.synthetic_clear_day):\n"
    "sinusoidal T_air 295.65 +- 3 K (maritime damping, max 15:00 local), RH from a 16 C dew\n"
    "point, half-sine DNI 880 / DHI 130 W m^-2 between 06:00 and 20:30 local, WIND 2.0-9.0 m/s\n"
    "peaking at 16:00 local, cloud 0.10, visibility 30 km. "
    "Not a measurement; a documented fixture (ADR 0032)."
)


def build():  # type: ignore[no-untyped-def]
    from irsim.thermal.weather_io import synthetic_clear_day

    return synthetic_clear_day(SAMPLE_START, **SAMPLE_ARGS)


def build_coastal():  # type: ignore[no-untyped-def]
    from irsim.thermal.weather_io import synthetic_clear_day

    return synthetic_clear_day(COASTAL_START, **COASTAL_ARGS)


def main() -> int:
    from irsim.thermal.weather_io import write_weather_csv

    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", type=pathlib.Path, default=None)
    ap.add_argument(
        "--which",
        choices=("inland", "coastal", "all"),
        default="all",
        help="inland is the original M6.2 fixture; coastal is the sea-breeze day the maritime "
        "scenes need (MM.6)",
    )
    args = ap.parse_args()

    jobs = []
    if args.which in ("inland", "all"):
        jobs.append((build(), args.out or DEFAULT_OUT, SAMPLE_COMMENT))
    if args.which in ("coastal", "all"):
        jobs.append((build_coastal(), args.out or COASTAL_OUT, COASTAL_COMMENT))
    if args.out is not None and len(jobs) > 1:
        ap.error("--out names one file, so pass --which inland or --which coastal with it")

    for series, out, comment in jobs:
        out.parent.mkdir(parents=True, exist_ok=True)
        write_weather_csv(series, out, comment=comment)
        print(f"wrote {out} ({series.n} rows, hash {series.content_hash[:12]})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
