#!/usr/bin/env python3
"""Generate the OH-Meinel airglow spectral shape M11.4 needs (docs/decisions/0065).

    python scripts/generate_airglow_spectrum.py --out data/spectra

Writes ``data/spectra/airglow_oh_meinel.csv``: a **relative** spectral shape s(lambda), not an
irradiance. The level is configuration (``environment.night.airglow_irradiance_*``, §5.5's
3.5-39 nW/cm2) and the shape says how it is distributed; ``irsim.radiometry.night`` normalises by
the shape's own integral, so the scale of the numbers in the file is arbitrary and a band takes
its own fraction rather than the whole level.

STATUS: MODELLED, NOT MEASURED. The night sky's near-infrared emission is dominated by the
Meinel bands of vibrationally excited OH, produced ~87 km up by H + O3 -> OH* + O2, plus the
O2(a1Delta-X) band at 1.27 um. The band HEADS below are spectroscopy -- they are where the
Delta-v = 1..4 sequences fall. The relative sequence STRENGTHS are the modelled quantity: roughly
55 / 27 / 12 / 6 percent of the near-infrared OH emission for Delta-v = 1, 2, 3, 4, which is the
usual ordering and magnitude. A measured sky spectrum (e.g. a Gemini/VLT near-IR sky model) should
replace this file; the loader and every consumer are unchanged by the swap.

The shape matters more than it looks. §5.5 says airglow "peaks between roughly 1 and 1.8 um, right
in the InGaAs response band" -- and the strongest sequence, Delta-v = 1, sits at 1.4-2.0 um, so a
standard 1.7 um InGaAs cut-off throws away much of it. That is a real design fact about SWIR night
imaging and it only exists in the model if the bands are in the right places.
"""

from __future__ import annotations

import argparse
import pathlib

import numpy as np
from numpy.typing import NDArray

LAMBDA_MIN_UM, LAMBDA_MAX_UM, LAMBDA_STEP_UM = 0.60, 2.60, 0.001
CONTINUUM_FRACTION = 0.04  # zodiacal + unresolved, flat in lambda

#: (centre um, width um, relative strength). Grouped by Delta-v sequence; strengths within a
#: sequence are shared equally, and the sequence totals are the modelled part.
SEQUENCES: dict[str, tuple[float, tuple[float, ...]]] = {
    # Delta-v = 1: (2,1) ... (9,8), 1.40-2.10 um -- the strongest, and mostly outside a 1.7 um cut
    "dv1": (0.55, (1.435, 1.505, 1.585, 1.670, 1.765, 1.875, 2.000)),
    # Delta-v = 2: (3,1) ... (9,7), 1.00-1.40 um
    "dv2": (0.27, (1.035, 1.090, 1.155, 1.230, 1.320)),
    # Delta-v = 3: 0.82-1.00 um
    "dv3": (0.12, (0.840, 0.875, 0.925, 0.975)),
    # Delta-v = 4: 0.70-0.80 um
    "dv4": (0.06, (0.715, 0.750, 0.790)),
}
BAND_WIDTH_UM = 0.018
#: O2(a1Delta - X3Sigma) at 1.27 um: the one strong non-OH feature in this range.
O2_BAND = (1.270, 0.010, 0.10)


def shape(lam: NDArray[np.float64]) -> NDArray[np.float64]:
    out = np.full_like(lam, CONTINUUM_FRACTION / (LAMBDA_MAX_UM - LAMBDA_MIN_UM))
    for total, centres in SEQUENCES.values():
        per_band = total / len(centres)
        for centre in centres:
            out += (
                per_band
                / (BAND_WIDTH_UM * np.sqrt(2.0 * np.pi))
                * np.exp(-0.5 * ((lam - centre) / BAND_WIDTH_UM) ** 2)
            )
    centre, width, strength = O2_BAND
    out += strength / (width * np.sqrt(2.0 * np.pi)) * np.exp(-0.5 * ((lam - centre) / width) ** 2)
    return np.asarray(out)


HEADER = """\
# Night-sky (airglow) RELATIVE spectral shape s(lambda). Columns: wavelength in MICROMETRES,
# relative spectral density per micrometre. The SCALE IS ARBITRARY -- the level comes from
# environment.night.airglow_irradiance_* (§5.5) and irsim.radiometry.night normalises by this
# file's own integral over {lo}-{hi} um, so a band takes its own fraction of the configured level
# rather than all of it (ADR 0065).
#
# STATUS: MODELLED, NOT MEASURED. Meinel bands of vibrationally excited OH (H + O3 -> OH* + O2 at
# ~87 km) plus the O2(a1Delta-X) band at 1.27 um. Band HEADS are spectroscopy; relative SEQUENCE
# strengths are modelled: Delta-v = 1/2/3/4 carry {d1:.0f}/{d2:.0f}/{d3:.0f}/{d4:.0f} % of the OH
# emission, with a flat {cont:.0f} % continuum for zodiacal and unresolved light. Replace with a
# measured near-infrared sky spectrum when one is available; nothing in the code changes.
#
# Model band fractions of the configured level:
{fractions}
# Generated by scripts/generate_airglow_spectrum.py on 2026-09-15 (roadmap M11.4).
wavelength_um,relative_density_per_um
"""


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", default="data/spectra")
    args = parser.parse_args(argv)
    out = pathlib.Path(args.out)
    out.mkdir(parents=True, exist_ok=True)

    lam = np.arange(LAMBDA_MIN_UM, LAMBDA_MAX_UM + 0.5 * LAMBDA_STEP_UM, LAMBDA_STEP_UM)
    s = shape(lam)
    total = float(np.trapezoid(s, lam))

    def frac(a: float, b: float) -> float:
        m = (lam >= a) & (lam <= b)
        return float(np.trapezoid(s[m], lam[m])) / total

    bands = (
        (0.75, 1.0, "NIR       0.75-1.00"),
        (0.9, 1.7, "SWIR      0.90-1.70"),
        (0.9, 2.5, "SWIR ext. 0.90-2.50"),
        (1.4, 2.0, "dv=1 peak 1.40-2.00"),
    )
    lines = "".join(f"#   {name}: {frac(a, b) * 100:5.1f} %\n" for a, b, name in bands)
    (out / "airglow_oh_meinel.csv").write_text(
        HEADER.format(
            lo=LAMBDA_MIN_UM,
            hi=LAMBDA_MAX_UM,
            d1=SEQUENCES["dv1"][0] * 100,
            d2=SEQUENCES["dv2"][0] * 100,
            d3=SEQUENCES["dv3"][0] * 100,
            d4=SEQUENCES["dv4"][0] * 100,
            cont=CONTINUUM_FRACTION * 100,
            fractions=lines,
        )
        + "\n".join(f"{a:.4f},{b:.6e}" for a, b in zip(lam, s, strict=True))
        + "\n",
        encoding="utf-8",
    )
    print(f"wrote {out / 'airglow_oh_meinel.csv'} ({len(lam)} rows), integral {total:.4f}")
    for a, b, name in bands:
        print(f"   {name}: {frac(a, b) * 100:5.1f} % of the configured level")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
