#!/usr/bin/env python3
"""Regenerate the committed synthetic weather sample (M6.2, ADR 0032).

    python scripts/generate_weather.py [--out data/weather/clear_midlat_summer_48h.csv]

The arguments below ARE the definition of the file; tests/unit/test_weather_io.py regenerates it
with the same call and requires a bit-exact match, so change them here and re-run.
"""

from __future__ import annotations

import argparse
import pathlib
import sys
from datetime import datetime, timezone

REPO = pathlib.Path(__file__).resolve().parents[1]
DEFAULT_OUT = REPO / "data" / "weather" / "clear_midlat_summer_48h.csv"

SAMPLE_ARGS: dict[str, float] = {
    "hours": 48.0,
    "utc_offset_h": 2.0,  # central European summer time: a mid-latitude June day
    "t_mean_k": 295.15,
    "t_swing_k": 12.0,
    "t_max_hour_local": 15.0,
    "dewpoint_k": 285.15,
    "wind_speed_m_s": 2.5,
    "cloud_fraction": 0.05,
    "dni_peak_w_m2": 850.0,
    "dhi_peak_w_m2": 110.0,
    "sunrise_hour_local": 5.5,
    "sunset_hour_local": 21.0,
    "visibility_m": 23000.0,
    "step_s": 3600.0,
}
SAMPLE_START = datetime(2024, 6, 21, 0, 0, tzinfo=timezone.utc)
SAMPLE_COMMENT = (
    "SYNTHETIC clear mid-latitude summer day, 48 h from 2024-06-21T00:00Z, local = UTC+2.\n"
    "Generated by scripts/generate_weather.py (irsim.thermal.weather_io.synthetic_clear_day):\n"
    "sinusoidal T_air 295.15 +- 6 K (max 15:00 local), RH from a 12 C dew point, half-sine\n"
    "DNI 850 / DHI 110 W m^-2 peak between 05:30 and 21:00 local, wind 2.5 m/s, cloud 0.05,\n"
    "visibility 23 km. Not a measurement; a documented fixture (ADR 0032)."
)


def build():  # type: ignore[no-untyped-def]
    from irsim.thermal.weather_io import synthetic_clear_day

    return synthetic_clear_day(SAMPLE_START, **SAMPLE_ARGS)


def main() -> int:
    from irsim.thermal.weather_io import write_weather_csv

    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", type=pathlib.Path, default=DEFAULT_OUT)
    args = ap.parse_args()
    series = build()
    args.out.parent.mkdir(parents=True, exist_ok=True)
    write_weather_csv(series, args.out, comment=SAMPLE_COMMENT)
    print(f"wrote {args.out} ({series.n} rows, hash {series.content_hash[:12]})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
